-- Menus exportés depuis sarah_gros
INSERT INTO tb_menu (id, designationmenu, page) VALUES
  (1, 'Caisse', 'PageCaisse'),
  (2, 'TABLEAU DE BORD', 'page_home'),
  (3, 'Article', 'PageArticle'),
  (4, 'Article Liste', 'page_listeArticle'),
  (5, 'Article Fournisseur', 'PageArticleFrs'),
  (6, 'Article Mouvement', 'PageArticleMouvement'),
  (7, 'Avoir', 'PageAvoir'),
  (8, 'Catégorie Articl', 'PageCategorieArticle'),
  (9, 'Catégorie Compt', 'PageCategorieCompte'),
  (10, 'Client', 'PageClient'),
  (11, 'Client Crédi', 'PageClientCredit'),
  (12, 'Commande Frs', 'PageCommandeFrs'),
  (13, 'Config DB', 'DatabaseConfig'),
  (14, 'Decaissement', 'PageDecaissement'),
  (15, 'Encaissement', 'PageEncaissement'),
  (16, 'DecaissementBq', 'PageDecaissementBq'),
  (17, 'EncaissementBq', 'PageEncaissementBq'),
  (18, 'Facture Liste', 'PageFactureListe'),
  (19, 'Fonction', 'PageFonction'),
  (20, 'Fournisseur', 'PageFournisseur'),
  (21, 'Fournisseur Dettes', 'PageFrsDette'),
  (22, 'Information Article', 'PageInfoArticle'),
  (23, 'Bon de Réceptio', 'PageBonReception'),
  (24, 'Magasin', 'PageMagasin'),
  (25, 'Menu', 'PageMenu'),
  (26, 'Paiement Client', 'PagePmtFacture'),
  (27, 'Paiement Fournisseur', 'PagePmtFrs'),
  (28, 'Prix Liste', 'PagePrixListe'),
  (29, 'Prix Saisie', 'PagePrixSaisie'),
  (30, 'Proforma', 'PageCommandeCli'),
  (31, 'Init DB', 'DBInitializerApp'),
  (32, 'Salaire Base', 'PageSalaireBase'),
  (33, 'Sauvegarde', 'PageSauvegarde'),
  (34, 'Sortie Article', 'PageSortie'),
  (35, 'Stock Article', 'PageStock'),
  (36, 'Transfert Article', 'PageTransfert'),
  (37, 'Transfert Banque', 'PageTransfertBanque'),
  (38, 'Transfert Caisse', 'PageTransfertCaisse'),
  (39, 'Taux Horaire', 'PageTauxHoraire'),
  (40, 'Type de paiement', 'PageTypePmt'),
  (41, 'Unité Articl', 'PageUnite'),
  (42, 'Users', 'PageUsers'),
  (43, 'Ventes', 'PageVente'),
  (44, 'Mouvement Stock', 'PageInfoMouvementStock'),
  (45, 'Autorisation', 'PageAutorisation'),
  (46, 'Liste Personnel', 'AppMain'),
  (47, 'Avance 15e', 'PageAVQ'),
  (48, 'Avance Spéciale', 'FenetreAvanceSpec'),
  (49, 'Nouveau SB', 'PageSalaireBase'),
  (50, 'Etat de Salaire', 'PageSalaireEtatSB'),
  (51, 'Salaire Horaire', 'PageEtatSalaireHoraire'),
  (52, 'Paiement Salaire', 'PageValidationSalaire'),
  (53, 'Utilisateurs', 'PageUsers'),
  (54, 'Suivi Commande', 'PageSuiviCommande'),
  (55, 'Prix d''article', 'PagePrixListe'),
  (56, 'Ajout Banque', 'PageBanqueNv'),
  (57, 'Banque', 'PageBanque'),
  (58, 'Base Liste', 'PageBaseListe'),
  (59, 'Ventes par Dépôt', 'PageVenteParMsin'),
  (60, 'Livraison Client', 'PageLivraisonClient'),
  (61, 'Stock Livraison', 'PageStockLivraison'),
  (62, 'Autorisation Admin', 'PageCodeAutorisation'),
  (63, 'Absence', 'PageAbsence'),
  (64, 'Facturation', 'PageFacturation'),
  (65, 'CHAT INTERNE', 'PageChat'),
  (66, 'Mouvement d''article', 'PageArticleMouvement'),
  (67, 'Liste Facture', 'PageFactureListe'),
  (68, 'Liste mouvements', 'PageListeMouvement'),
  (69, 'Prix de revient', 'PagePrixRevient'),
  (70, 'Péremption d''article', 'PageGestionPeremption'),
  (71, 'Stock Alerte', 'PageStockAlerte'),
  (72, 'Inventaire du Jour', 'PageInventaireJour'),
  (73, 'Marge Commerciale', 'PageStock'),
  (74, 'Suivi de présence', 'PageSuiviPresence'),
  (75, 'Gérer Personnels', 'PagePersonnelCRUD'),
  (76, 'Présence Personnel', 'PagePresencePersonnel'),
  (77, 'Présence', 'PagePresence'),
  (78, 'Evenements', 'PageEvenement'),
  (79, 'BLOC: TABLEAU DE BORD', ''),
  (80, 'BLOC: CHAT INTERNE', ''),
  (81, 'BLOC: COMMERCIALE', ''),
  (82, 'BLOC: PERSONNEL', ''),
  (83, 'BLOC: TRÉSORERIE', ''),
  (84, 'BLOC: BASE DE DONNÉES', ''),
  (85, 'Paramètres', ''),
  (86, 'Historiques livraison', ''),
  (87, 'Bon de Livraison', '');

INSERT INTO tb_autorisation (idfonction, idmenu) VALUES
  (1, 1),
  (1, 2),
  (1, 4),
  (1, 10),
  (1, 18),
  (1, 19),
  (1, 20),
  (1, 24),
  (1, 25),
  (1, 33),
  (1, 35),
  (1, 37),
  (1, 38),
  (1, 39),
  (1, 44),
  (1, 45),
  (1, 46),
  (1, 47),
  (1, 48),
  (1, 49),
  (1, 50),
  (1, 51),
  (1, 52),
  (1, 53),
  (1, 55),
  (1, 56),
  (1, 57),
  (1, 58),
  (1, 59),
  (1, 60),
  (1, 61),
  (1, 62),
  (1, 65),
  (1, 66),
  (1, 67),
  (1, 68),
  (1, 69),
  (1, 70),
  (1, 71),
  (1, 72),
  (1, 73),
  (1, 74),
  (1, 78),
  (1, 79),
  (1, 80),
  (1, 81),
  (1, 82),
  (1, 83),
  (1, 84),
  (1, 85);